name: deploy-docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  deployments: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Export drawio files to png files
        uses: rlespinasse/drawio-export-action@v2.5.0
        with:
          format: png
          transparent: true
          output: /tmp/images
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: images
          path: /tmp/images

  build-docs:
    runs-on: ubuntu-latest
    needs: render-diagrams
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download images from render-diagrams
        uses: actions/download-artifact@v3
        with:
          name: images
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true
      - name: Build 'public' folder ready for deployment
        working-directory: ./docs
        run: bundle exec middleman build
      - name: Publish
        uses: actions/upload-pages-artifact@v1
        with:
          PATH: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v1
        id: deployment
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}