name: Export drawio files to png and keep updates synchronised
on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]
    paths:
      - "**.drawio"
      - .github/workflows/drawio-export.yaml
concurrency:
  group: drawio-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  drawio-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Draw.io Export Action
        uses: rlespinasse/drawio-export-action@v2.5.0
        with:
          # Path to the drawio files to export
          path: docs
          # Exported format [default: pdf] [possible values: adoc, jpg, pdf, png, svg, vsdx, xml]
          format: png
          # Exported folder name (default location is same a path above)
          output: sources/images

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1
        if: github.ref == 'refs/heads/main'

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: sync drawio exported files"
          commit_user_name: "${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          commit_user_email: "${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"
        if: github.ref == 'refs/heads/main'